fix: address issues reported by `pytest`
First, it seems `debug_tablefinder` doesn't accept keywork argument `tf`
anymore, so just remove it:

    >       image.debug_tablefinder(tf=self.pdf_table_extraction_settings)  # debug
    E       TypeError: PageImage.debug_tablefinder() got an unexpected keyword argument 'tf'

    beancount_reds_importers/libreader/pdfreader.py:120: TypeError

Second, ofxparse seems to call a deprecated method, creating plenty of
log warnings:

    .../site-packages/ofxparse/ofxparse.py:445: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
    stmtrs_ofx = ofx.findAll('stmtrs')